version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: ng1
    ports:
      - "8080:8080"
      - "8888:8888"
    volumes:
      - /home/osboxes/code/nginx/nginx-html:/usr/share/nginx/html
      - /home/osboxes/code/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/osboxes/code/images/:/etc/nginx/images
    restart: always
